server:
  port: 8091
spring:
  kafka:
    consumer:
      group-id: demo
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092
kafka:
  isDebug: true
  topics:
    partitions: 1
    replication-factor: 1
    demo: message-test
